# Generated by Django 5.2.5 on 2025-08-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
    ]
