# Generated by Django 5.2.5 on 2025-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_remove_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_length',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
