# Generated by Django 5.2.5 on 2025-08-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('displacement', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('top_speed', models.IntegerField()),
                ('acceleration', models.FloatField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
